/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package daq.tokens.internal;

public class JDaqTokens {
  public static boolean enabled() {
    return JDaqTokensJNI.enabled();
  }

  public static String acquire(Mode mode) throws daq.tokens.AcquireTokenException {
    return JDaqTokensJNI.acquire__SWIG_0(mode.swigValue());
  }

  public static String acquire() throws daq.tokens.AcquireTokenException {
    return JDaqTokensJNI.acquire__SWIG_1();
  }

}
