/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package daq.tokens.internal;

public class JDaqTokensJNI {
  public final static native boolean enabled();
  public final static native String acquire__SWIG_0(int jarg1) throws daq.tokens.AcquireTokenException;
  public final static native String acquire__SWIG_1() throws daq.tokens.AcquireTokenException;
}
